### ISSUE TITLE
Add Themes 

### ISSUE THREAD

**Issue by ncvescera** [ncvescera/GayPass#10]
Add more themes (background and color sets).

Need your graphic abilities @CiroSimonetti !

**Comment by CiroSimonetti** [comment]
Ma se aggiungessimo anche una Dark Mode?

**Comment by ncvescera** [comment]
This code could be usefull

```kotlin
tmp.buttonTintList = ColorStateList.valueOf(ContextCompat.getColor(context, primaryColor))
```

**Comment by ncvescera** [comment]
We have enough themes for the moment.
